#!/bin/sh

read cpu user nice system idle iowait irq softirq steal _ < /proc/stat
prev_idle=$idle
prev_total=$((user + nice + system + idle + iowait + irq + softirq + steal))

sleep 1

read cpu user nice system idle iowait irq softirq steal _ < /proc/stat
total=$((user + nice + system + idle + iowait + irq + softirq + steal))

diff_total=$((total - prev_total))
diff_idle=$((idle - prev_idle))

usage=$((100 * (diff_total - diff_idle) / diff_total))

printf 'CPU: %s%%\n' "$usage"
