bar:
  height: 24
  location: top
  background: 1e1e2eff
  font: monospace:pixelsize=12

  left:
    - script:
        path: ~/.config/yambar/niri-workspaces.sh
        content:
          string:
            text: " {ws} "
            foreground: 89b4faff

  center:
    - script:
        path: /bin/sh
        args: ["-c", "while true; do echo \"time|string|$(date +'%Y-%m-%d  %H:%M:%S')\"; echo; sleep 5; done"]
        content:
          string:
            text: "{time}"
            foreground: cdd6f4ff
  right:
      - cpu:
          poll-interval: 1000
          content:
            map:
              conditions:
                'id == -1':
                  string:
                    text: "CPU: {cpu}%"
                    foreground: a6e3a1ff

      - script:
          poll-interval: 2000
          path: /bin/sh
          args:
            - "-c"
            - |
              free -m | awk 'NR==2 {
                printf "ram_used|string|%.1f\nram_total|string|%.1f\n\n", $3/1024, $2/1024
              }'
          content:
            string:
              text: " | RAM: {ram_used} / {ram_total} GiB "
              foreground: fab387ff
